# configs/yolov8.yaml

model_name: "YOLOv8"
model_type: "ultralytics"
model_architecture: "yolov8s.pt"
epochs: 50
img_size: 640
batch: 16
data_yaml: "datasets/data.yaml"
weights_dir: "weights"
results_dir: "runs/detect"